export enum CalcActions {
  ADD_ELEMENT = 'ADD_ELEMENT',
  SET_WIDGET = 'SET_WIDGET',
  UPDATE_ELEMENT = 'UPDATE_ELEMENT',
  ARRANGE_ELEMENTS = 'ARRANGE_ELEMENTS',
  DELETE_ELEMENT = 'DELETE_ELEMENT',
  UPDATE_FORMULA = 'UPDATE_FORMULA',
  UPDATE_RES_DESC = 'UDPATE_RES_DESC',
  UPDATE_RES_VAL = 'UPDATE_RES_VAL',
}
